<?php

namespace ptlis\DoctrineTestcaseBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Street
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Street extends EntityRepository
{
}
